// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ListMessagesRequest struct {
	Page    int64  `form:"page,default=1"`
	Size    int64  `form:"size,default=20"`
	Status  string `form:"status,options=all|unread|sent,default=all"`
	Channel string `form:"channel,options=personal|system,default=personal"`
	UserId  int64  `json:"-"`
}

type ListMessagesResponse struct {
	Items []Message `json:"items"`
	Total int64     `json:"total"`
	Page  int64     `json:"page"`
	Size  int64     `json:"size"`
}

type MarkReadRequest struct {
	Id      int64  `path:"id"`
	Channel string `json:"channel,options=personal|system,default=personal"`
	UserId  int64  `json:"-"`
}

type Message struct {
	Id         int64  `json:"id"`
	SenderId   int64  `json:"senderId"`
	ReceiverId int64  `json:"receiverId"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	IsRead     bool   `json:"isRead"`
	ReadAt     string `json:"readAt,optional"`
	CreatedAt  string `json:"createdAt"`
	Channel    string `json:"channel"`
	Priority   string `json:"priority,optional"`
}

type SendMessageRequest struct {
	Channel    string `json:"channel,options=personal|system,default=personal"`
	SenderId   int64  `json:"senderId,optional"`
	ReceiverId int64  `json:"receiverId,required"`
	Title      string `json:"title,optional"`
	Content    string `json:"content,required"`
	Priority   string `json:"priority,options=info|warning|critical,default=info"`
}

type UnreadCountRequest struct {
	UserId int64 `json:"-"`
}

type UnreadCountResponse struct {
	Personal int64 `json:"personal"`
	System   int64 `json:"system"`
	Total    int64 `json:"total"`
}

type RegisterRequest struct {
	Username string `json:"username,required"`
	Password string `json:"password,required"`
}

type LoginRequest struct {
	Username string `json:"username,required"`
	Password string `json:"password,required"`
}

type User struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}

type AuthResponse struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}
