// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/pineapple/msg-demo/backend/inbox/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{
				serverCtx.AuthMiddleware.Handle,
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/v1/messages",
				Handler: SendMessageHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodGet,
				Path:    "/api/v1/messages",
				Handler: ListMessagesHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/v1/messages/:id/read",
				Handler: MarkMessageReadHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodGet,
				Path:    "/api/v1/messages/unread/count",
				Handler: UnreadCountHandler(serverCtx),
			},
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/login",
				Handler: LoginHandler(serverCtx),
			},
		},
	)
}
